name: GitHub Pagesへのデプロイ
on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ブランチをチェックアウト
        uses: actions/checkout@v2
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarnのキャッシュディレクトリパスを取得
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: node_modulesキャッシュ設定
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: ビルドキャッシュの設定
        uses: actions/cache@v1
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-${{ github.ref }}-cache
      - name: デプロイ
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
